GET http://localhost:3000/api/todos/
###
POST http://localhost:3000/api/todos
Content-Type: application/json

{
    "title": "test",
    "description": "loremipsumdolersitamer"
}
###
DELETE  http://localhost:3000/api/todos
Content-Type: application/json

{
    "id": "66d5bb1b81448a0421e512dd"
}
###
DELETE  http://localhost:3000/api/todos
###
PATCH http://localhost:3000/api/todos
Content-Type: application/json

{
    "id": "66d31510769b786a621b6335",
    "title": "123132"
}